language: php

php:
  - 5.3
  - 5.4

env:
  - DB=application

before_script:
  - "sudo apt-get install lighttpd"
  - "curl -v http://127.0.0.1/codeigniter"

script: phpunit --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - master
    - application-tests