language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite
  - DB=application

before_script:
  - pyrus install http://pear.phpunit.de/get/PHPUnit_Selenium-1.2.6.tgz
  - pyrus install http://pear.php-tools.net/get/vfsStream-0.11.2.tgz
  - phpenv rehash
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"
  - sh -c "if [ '$DB' = 'application' ]; then wget http://selenium.googlecode.com/files/selenium-server-standalone-2.21.0.jar; fi"
  - sh -c "if [ '$DB' = 'application' ]; then echo '#!/bin/sh' >> selenium.sh; fi"
  - sh -c "if [ '$DB' = 'application' ]; then echo 'java -jar selenium-server-standalone-2.21.0.jar' >> selenium.sh; fi"
  - sh -c "if [ '$DB' = 'application' ]; then sudo chmod +x selenium.sh >> selenium.sh; fi"
  - sh -c "if [ '$DB' = 'application' ]; then nohup ./selenium.sh '&'; fi"

script: phpunit --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - master
    - application-tests