language: php

php:
  - 5.3
  - 5.4

env:
  - DB=application

before_script:
  - "sudo apt-get install lighttpd"
  - "sudo apt-get install php5-cgi"
  - "sudo echo 'cgi.fix_pathinfo = 1' >> /etc/php5/cgi/php.ini"
  - sudo echo 'fastcgi.server = ( ".php" => ((' >> /etc/lighttpd/lighttpd.conf
  - sudo echo '"bin-path" => "/usr/bin/php5-cgi",' >> /etc/lighttpd/lighttpd.conf
  - sudo echo '"socket" => "/tmp/php.socket"' >> /etc/lighttpd/lighttpd.conf
  - sudo echo ')))' >> /etc/lighttpd/lighttpd.conf
  - sudo /etc/init.d/lighttpd restart
  - "sleep 4"
  - "sudo mkdir /var/www/codeigniter"
  - "sudo chmod 777 /var/www/codeigniter -R"
  - "sudo cp index.php /var/www/codeigniter/index.php"
  - "sudo cp application/ /var/www/codeigniter/ -r"
  - "sudo cp system/ /var/www/codeigniter/ -r"
  - "curl -v http://127.0.0.1/codeigniter"

script: phpunit --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - master
    - application-tests