language: php

php:
  - 5.3
  - 5.4

env:
  - DB=application

before_script:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y -qq install apache2"
  - "sudo apt-get -y -qq install libapache2-mod-php5"
  - sudo a2enmod php5
  - sudo /etc/init.d/apache2 restart
  - "sleep 5"
  - ls /var/www
  - "curl -v http://127.0.0.1/"


script: phpunit --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - master
    - application-tests