language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite
  - DB=application

before_script:
  - curl -v localhost

script: phpunit --configuration tests/travis/$DB.phpunit.xml

branches:
  only:
    - develop
    - master
    - application-tests